#!/bin/bash

if ! [[ $1 ]]
then
    echo "Error: Backup name missing"
    echo "Please specify a backup name, e.g. 'restore 20141104'"
    echo "Finished: FAILURE"
    exit 1
fi

if [ -z "$ODOO_DB_NAME" ]; then echo "Error: ODOO_DB_NAME not set"; echo "Finished: FAILURE"; exit 1; fi

if ! [[ $1 =~ ^[a-zA-Z0-9_-]+$ ]]
then
  echo "The given backup name does not match the expected pattern: only characters, digits, underscore and dash are allowed ([a-zA-Z0-9_-])."
  echo 'Finished: FAILURE'
  exit 1
fi

FILES_ARCHIVE="/backups/backup_$1.zip"

if [[ ! -f $FILES_ARCHIVE ]]
then
  echo "The file $FILES_ARCHIVE does not exist. Aborting."
  echo "Finished: FAILURE."
  exit 1
fi

echo $ODOO_DB_NAME
echo $ADMIN_PASSWORD


curl -F "master_pwd="${ADMIN_PASSWORD} -F "backup_file=@"${FILES_ARCHIVE} -F 'copy=true' -F 'name='${ODOO_DB_NAME} http://odoo:8069/web/database/restore


#curl -F 'master_pwd=admin' -F backup_file=@/backups/backup_latest.zip -F 'copy=true' -F 'name=db3' http://odoo:8069/web/database/restore

echo 'Finished: SUCCESS'