<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Beste Centaurianen Vanaf vandaag zijn er weer lidkaarten te koop in &#8216;t Bunkertje. Voor 7 euro kun je de rest van het jaar weer genieten van kortingen op onze activiteiten. Allen daarheen dus.</title>
	<atom:link href="http://www.centaura.be/beste-centaurianen-vanaf-vandaag-zijn-er-weer-lidkaarten-te-koop-in-t-bunkertje-voor-7-euro-kun-je-de-rest-van-het-jaar-weer-genieten-van-kortingen-op-onze-activiteiten-allen-daarheen-dus/feed/" rel="self" type="application/rss+xml" />
	<link>http://www.centaura.be/beste-centaurianen-vanaf-vandaag-zijn-er-weer-lidkaarten-te-koop-in-t-bunkertje-voor-7-euro-kun-je-de-rest-van-het-jaar-weer-genieten-van-kortingen-op-onze-activiteiten-allen-daarheen-dus/</link>
	<description></description>
	<lastBuildDate></lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.3</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.527 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-10-17 11:53:51 -->
