<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Beste mensen Zin om Centaura te helpen ? Kom af naar de lange munt in sportieve kledij ;)</title>
	<atom:link href="http://www.centaura.be/beste-mensen-zin-om-centaura-te-helpen-kom-af-naar-de-lange-munt-in-sportieve-kledij/feed/" rel="self" type="application/rss+xml" />
	<link>http://www.centaura.be/beste-mensen-zin-om-centaura-te-helpen-kom-af-naar-de-lange-munt-in-sportieve-kledij/</link>
	<description></description>
	<lastBuildDate></lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.3</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.529 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-10-17 11:53:52 -->
