version: "3.5"
services:
  nginx:
    build:
      context: .
      dockerfile: ./config/docker/nginx/Dockerfile
    links: ["odoo", "wordpress", "phpmyadmin"]
    depends_on: ["odoo"]
    env_file:
      - ./.env
    ports: ["80:80"]
    restart: always
  mysql:
    build:
      context: .
      dockerfile: ./config/docker/mysql/Dockerfile

    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks: ["default"]
    env_file:
      - ./.env

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress:
    build:
      context: .
      dockerfile: ./config/docker/wordpress/Dockerfile
    volumes:
      - ./volumes/wordpress:/var/www/html
    restart: always
    networks: ["default"]
    depends_on:
      - mysql
    links:
      - mysql
    env_file:
      - ./.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8181:80
    links:
      - mysql
    restart: on-failure
    networks: ["default"]
    env_file:
      - ./.env

  odoo:
    build:
      context: .
      dockerfile: ./config/docker/odoo/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./volumes/odoo:/var/lib/odoo

    ports:
      - "8069:8069"
    networks: ["default"]
    env_file:
      - ./.env

  postgres:
    image: postgres:9.4
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/pgdata
    networks: ["default"]
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  phppgadmin:
    image: dockage/phppgadmin:latest
    depends_on:
      - postgres
    ports:
      - 8282:80
    links:
      - postgres
    restart: on-failure
    networks: ["default"]
    env_file:
      - ./.env

  backup:
    image: aveltens/wordpress-backup
    restart: always
    volumes:
      - ./backups/wordpress/:/backups
      - ./volumes/wordpress:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_ENV_MYSQL_DATABASE=$WORDPRESS_DB_NAME
      - MYSQL_ENV_MYSQL_USER=$WORDPRESS_DB_USER
      - MYSQL_ENV_MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD
      - MYSQL_PORT_3306_TCP_PORT=3306
      - BACKUP_TIME=$WORDPRESS_BACKUPTIME

networks:
  default:
    name: server
    driver: bridge
